### ISSUE TITLE
Noise Remover scale selection

### ISSUE THREAD

**Issue by NathanDreamweaver** [ebiiim/anime2x#17]
As of now, you can't choose between the values of "0" "1" "2" and "3" in noise remover, it defaulting to 1. A parameter to do so would be appreciated.

**Comment by ebiiim** [comment]
Good idea!
Now you can do it with the new version [v0.4.0](https://github.com/nullpo-t/anime2x/releases/tag/v0.4.0).

**Comment by NathanDreamweaver** [comment]
Thank you! :)
